version: "3.1"
services:
  domain-system:
    image: docker.pkg.github.com/zemoso-int/bootcamp-11/bootcamp11-domain-management:dev-domain-1.0
    ports:
      - "9000:8080"
    environment:
      POSTGRES_HOST: dockerhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: digital_asset_management
      POSTGRES_USER: security_officer
      POSTGRES_PASSWORD: s3cur1ty_0ff1c3r
    network_mode: host

  gsuite-system:
    image: docker.pkg.github.com/zemoso-int/bootcamp-11/bootcamp11-gsuite:dev-gsuite-2.0
    ports:
      - "8080:8081"
    network_mode: host

  frontend:
    image: docker.pkg.github.com/zemoso-int/bootcamp-11/bootcamp11-frontend:dev-frontend-2.0
    ports:
      - "8081:80"
